include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore  # suppress drift annotation warnings

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - use_super_parameters
